name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Run Scarb Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
